kind = "web"
previewPath = "/"
title = "OrahWeb"
version = "1.0.0"
id = "artifacts/orahweb"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/", "/api/auth", "/api/contact", "/api/user", "/api/register" ]
localPort = 19637

[services.development]
run = "pnpm --filter @workspace/orahweb run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/orahweb", "run", "build" ]
run = "pnpm --filter @workspace/orahweb run start"

[services.env]
PORT = "19637"
